// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSx2_0pjjwIeEDUVoovAxnyVTBX8ovACQ',
    appId: '1:38583168881:web:f2c939734fc092e051d0d0',
    messagingSenderId: '38583168881',
    projectId: 'social-check-7fbcb',
    authDomain: 'social-check-7fbcb.firebaseapp.com',
    storageBucket: 'social-check-7fbcb.firebasestorage.app',
    measurementId: 'G-HCJYSM7J74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx7VM8r2BvdyO-ppDAURshO4gHoiMQCFE',
    appId: '1:38583168881:android:c61716a8d7b9df1751d0d0',
    messagingSenderId: '38583168881',
    projectId: 'social-check-7fbcb',
    storageBucket: 'social-check-7fbcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT6Ic8WlD9y3SaEzMOQi6WZDdF-UTCJPs',
    appId: '1:38583168881:ios:9d027f7ac9c6232e51d0d0',
    messagingSenderId: '38583168881',
    projectId: 'social-check-7fbcb',
    storageBucket: 'social-check-7fbcb.firebasestorage.app',
    iosBundleId: 'com.example.socialCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT6Ic8WlD9y3SaEzMOQi6WZDdF-UTCJPs',
    appId: '1:38583168881:ios:9d027f7ac9c6232e51d0d0',
    messagingSenderId: '38583168881',
    projectId: 'social-check-7fbcb',
    storageBucket: 'social-check-7fbcb.firebasestorage.app',
    iosBundleId: 'com.example.socialCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSx2_0pjjwIeEDUVoovAxnyVTBX8ovACQ',
    appId: '1:38583168881:web:ca1aea4cec7101e551d0d0',
    messagingSenderId: '38583168881',
    projectId: 'social-check-7fbcb',
    authDomain: 'social-check-7fbcb.firebaseapp.com',
    storageBucket: 'social-check-7fbcb.firebasestorage.app',
    measurementId: 'G-VJGVZH8V8G',
  );
}
